/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.eventmaster.pro;

import com.mycompany.eventmaster.pro.EventMasterSystem;
import com.mycompany.eventmaster.pro.EventBase;
import com.mycompany.eventmaster.pro.Artist;

/**
 *
 * @author Uer
 */
public class AssociateArtistPanelForm extends javax.swing.JPanel {

    private EventMasterSystem system;

    /**
     * Creates new form AssociateArtistPanelForm
     */
    public AssociateArtistPanelForm(EventMasterSystem system) {
        this.system = system;
        initComponents();
        populateComboBoxes();
        jButtonAssociate.addActionListener(e -> associateArtist());
    }

    private void populateComboBoxes() {
        jComboBoxEvent.removeAllItems();
        for (EventBase event : system.getEvents()) {
            jComboBoxEvent.addItem(event.getName());
        }
        jComboBoxArtist.removeAllItems();
        for (Artist artist : system.getArtists()) {
            jComboBoxArtist.addItem(artist.getName());
        }
    }

    private void associateArtist() {
        String eventName = (String) jComboBoxEvent.getSelectedItem();
        String artistName = (String) jComboBoxArtist.getSelectedItem();
        if (eventName == null || artistName == null) {
            jLabelResult.setText("Select event and artist.");
            return;
        }
        EventBase selectedEvent = null;
        Artist selectedArtist = null;
        for (EventBase event : system.getEvents()) {
            if (event.getName().equals(eventName)) {
                selectedEvent = event;
                break;
            }
        }
        for (Artist artist : system.getArtists()) {
            if (artist.getName().equals(artistName)) {
                selectedArtist = artist;
                break;
            }
        }
        if (selectedEvent != null && selectedArtist != null) {
            selectedEvent.addArtist(selectedArtist);
            jLabelResult.setText("Artist associated.");
        } else {
            jLabelResult.setText("Error associating artist.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxEvent = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxArtist = new javax.swing.JComboBox<>();
        jButtonAssociate = new javax.swing.JButton();
        Result = new javax.swing.JLabel();
        jLabelResult = new javax.swing.JLabel();

        jLabel1.setText("Select Event:");

        jLabel2.setText("Select Artist:");

        jButtonAssociate.setText("Associate Artist");

        Result.setText("Result:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jButtonAssociate, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAssociate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Result;
    private javax.swing.JButton jButtonAssociate;
    private javax.swing.JComboBox<String> jComboBoxArtist;
    private javax.swing.JComboBox<String> jComboBoxEvent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelResult;
    // End of variables declaration//GEN-END:variables
}
