/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.eventmaster.pro;

/**
 * Desarrolladores:
 *         - Isabella Gómez Parra.
 *         - Daniel Eduardo González Palacio.
 *
 */
public class CreateEventPanelForm extends javax.swing.JPanel {

    private EventMasterSystem system;
    /**
     * Creates new form CreateEventPanelForm
     */
    public CreateEventPanelForm(EventMasterSystem system) {
        this.system = system;
        initComponents();
        jComboBoxLocation.removeAllItems();

        for (Location loc : system.getLocations()) {
            jComboBoxLocation.addItem(loc.getName());
        }

        jButtonCreateEvent.addActionListener(e -> {
            String name = jTextFEventName.getText();
            String date = jTextFEventDate.getText();
            String time = jTextFEventTime.getText();
            String category = jTextFEventCategory.getText();
            String budgetStr = jTextFEventBudget.getText();
            String locationName = (String) jComboBoxLocation.getSelectedItem();
            Location selectedLocation = null;

            for (Location loc : system.getLocations()) {
                if (loc.getName().equalsIgnoreCase(locationName)) {
                    selectedLocation = loc;
                    break;
                }
            }

            if (name.isEmpty() || date.isEmpty() || time.isEmpty() || category.isEmpty() || budgetStr.isEmpty() || selectedLocation == null) {
                jLabelResult.setText("Please fill all fields correctly.");
                return;
            }

            double budget;

            try {
                budget = Double.parseDouble(budgetStr);
            } catch (NumberFormatException ex) {
                jLabelResult.setText("Invalid budget.");
                return;
            }

            EventBase newEvent;

            if (category.equalsIgnoreCase("Concert")) {
                newEvent = new ConcertEvent(name, date, time, selectedLocation, budget);
            } else if (category.equalsIgnoreCase("Conference")) {
                newEvent = new ConferenceEvent(name, date, time, selectedLocation, budget);
            } else {
                jLabelResult.setText("Invalid category. Use Concert or Conference.");
                return;
            }

            system.createEvent(newEvent);
            jLabelResult.setText("Event created successfully!");
            jTextFEventName.setText("");
            jTextFEventDate.setText("");
            jTextFEventTime.setText("");
            jTextFEventCategory.setText("");
            jTextFEventBudget.setText("");
        });
    }

    public void refreshLocations() {
        jComboBoxLocation.removeAllItems();
        for (Location loc : system.getLocations()) {
            jComboBoxLocation.addItem(loc.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFEventName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFEventDate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFEventTime = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFEventCategory = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFEventBudget = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxLocation = new javax.swing.JComboBox<>();
        jButtonCreateEvent = new javax.swing.JButton();
        Result = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelResult = new javax.swing.JLabel();

        jLabel1.setText("Event Name:");

        jLabel2.setText("Event Date (yyyy-mm-dd):");

        jLabel3.setText("Event Time (hh:mm):");

        jLabel4.setText("Event Category (Concert/Conference):");

        jLabel5.setText("Event Budget:");

        jLabel6.setText("Location:");

        jButtonCreateEvent.setText("Create Event");

        Result.setText("Result:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jComboBoxLocation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                        .addComponent(jTextFEventCategory, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFEventTime, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFEventDate, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFEventName, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFEventBudget, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonCreateEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFEventName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFEventDate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFEventTime, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFEventCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFEventBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButtonCreateEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Result;
    private javax.swing.JButton jButtonCreateEvent;
    private javax.swing.JComboBox<String> jComboBoxLocation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelResult;
    private javax.swing.JTextField jTextFEventBudget;
    private javax.swing.JTextField jTextFEventCategory;
    private javax.swing.JTextField jTextFEventDate;
    private javax.swing.JTextField jTextFEventName;
    private javax.swing.JTextField jTextFEventTime;
    // End of variables declaration//GEN-END:variables
}
