/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.eventmaster.pro;

import com.mycompany.eventmaster.pro.EventBase;
import com.mycompany.eventmaster.pro.EventMasterSystem;
import com.mycompany.eventmaster.pro.Sale;
import com.mycompany.eventmaster.pro.Ticket;

/**
 *
 * @author Uer
 */
public class ManageTicketsSalesPanelForm extends javax.swing.JPanel {
    private EventMasterSystem system;

    /**
     * Creates new form ManageTicketsSalesPanelForm
     */
    public ManageTicketsSalesPanelForm(EventMasterSystem system) {
        this.system = system;
        initComponents();
        populateEvents();
        jButtonSellTicket.addActionListener(e -> sellTicket());
        jButtonShowSales.addActionListener(e -> showSales());
    }

    private void populateEvents() {
        jComboBoxEvent.removeAllItems();
        for (EventBase event : system.getEvents()) {
            jComboBoxEvent.addItem(event.getName());
        }
    }

    private void sellTicket() {
        String ticketType = jTextFTicketType.getText().trim();
        String ticketPriceStr = jTextFTicketPrice.getText().trim();
        String eventName = (String) jComboBoxEvent.getSelectedItem();
        String buyerName = jTextFBuyerName.getText().trim();
        String purchaseDate = jTextFPurchaseDate.getText().trim();
        if (ticketType.isEmpty() || ticketPriceStr.isEmpty() || eventName == null || buyerName.isEmpty() || purchaseDate.isEmpty()) {
            jLabelResult.setText("Please fill all fields.");
            return;
        }
        double price;
        try {
            price = Double.parseDouble(ticketPriceStr);
        } catch (NumberFormatException ex) {
            jLabelResult.setText("Invalid price.");
            return;
        }
        EventBase event = null;
        for (EventBase ev : system.getEvents()) {
            if (ev.getName().equals(eventName)) {
                event = ev;
                break;
            }
        }
        if (event == null) {
            jLabelResult.setText("Event not found.");
            return;
        }
        Ticket ticket = new Ticket(ticketType, price); // El constructor correcto solo acepta tipo y precio
        system.registerTicket(ticket);
        Sale sale = new Sale(ticket, buyerName, purchaseDate);
        system.registerSale(event, sale);
        jLabelResult.setText("Ticket sold successfully.");
        clearFields();
    }

    private void showSales() {
        StringBuilder sb = new StringBuilder();
        for (Sale sale : system.getSales()) {
            sb.append("Type: ").append(sale.getTicket().getType())
              .append(" | Buyer: ").append(sale.getBuyerName())
              .append(" | Date: ").append(sale.toString().contains("Date") ? sale.toString().split("Date: ")[1] : "")
              .append(" | Price: $").append(sale.getTicket().getPrice())
              .append("\n");
        }
        jTextAreaSales.setText(sb.toString());
    }

    private void clearFields() {
        jTextFTicketType.setText("");
        jTextFTicketPrice.setText("");
        jTextFBuyerName.setText("");
        jTextFPurchaseDate.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFTicketType = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFTicketPrice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxEvent = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextFBuyerName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFPurchaseDate = new javax.swing.JTextField();
        jButtonSellTicket = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSales = new javax.swing.JTextArea();
        jButtonShowSales = new javax.swing.JButton();
        Result = new javax.swing.JLabel();
        jLabelResult = new javax.swing.JLabel();

        jLabel1.setText("Ticket Type:");

        jLabel2.setText("Ticket Price:");

        jLabel3.setText("Event Name:");

        jLabel4.setText("Buyer Name:");
        jLabel4.setToolTipText("");

        jLabel5.setText("Purchase Date:");

        jButtonSellTicket.setText("Sell Ticket");

        jLabel6.setText("Show all sales:");

        jTextAreaSales.setColumns(20);
        jTextAreaSales.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSales);

        jButtonShowSales.setText("Show All Sales");

        Result.setText("Result:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonShowSales, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jComboBoxEvent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFTicketType)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFTicketPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextFBuyerName, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextFPurchaseDate, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(jButtonSellTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFTicketType, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFTicketPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFBuyerName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFPurchaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButtonSellTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonShowSales, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Result;
    private javax.swing.JButton jButtonSellTicket;
    private javax.swing.JButton jButtonShowSales;
    private javax.swing.JComboBox<String> jComboBoxEvent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelResult;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaSales;
    private javax.swing.JTextField jTextFBuyerName;
    private javax.swing.JTextField jTextFPurchaseDate;
    private javax.swing.JTextField jTextFTicketPrice;
    private javax.swing.JTextField jTextFTicketType;
    // End of variables declaration//GEN-END:variables
}
