/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.eventmaster.pro;

/**
 *
 * @author Uer
 */
public class ManageArtistsPanelForm extends javax.swing.JPanel {
    private EventMasterSystem system;

    /**
     * Creates new form ManageArtistsPanelForm
     */
    public ManageArtistsPanelForm(EventMasterSystem system) {
        this.system = system;
        initComponents();
        jButtonAddArtist.addActionListener(e -> addArtist());
        jButtonShowArtists.addActionListener(e -> showArtists());
    }

    private void addArtist() {
        String name = jTextFArtistName.getText().trim();
        String contact = jTextFContactInfo.getText().trim();
        String techReq = jTextFTechReq.getText().trim();
        String pastEvents = jTextFPastEvents.getText().trim();
        if (name.isEmpty() || contact.isEmpty()) {
            jLabelResult.setText("Please enter artist name and contact info.");
            return;
        }
        Artist artist = new Artist(name, contact, techReq);
        if (!pastEvents.isEmpty()) {
            String[] past = pastEvents.split(",");
            for (String p : past) {
                artist.addPastEvent(p.trim());
            }
        }
        system.registerArtist(artist);
        jLabelResult.setText("Artist added successfully.");
        clearFields();
    }

    private void showArtists() {
        StringBuilder sb = new StringBuilder();
        for (Artist a : system.getArtists()) {
            sb.append(a.getName()).append(" | ")
              .append(a.getContactInfo()).append(" | ")
              .append(a.getTechnicalRequirements()).append(" | Past: ")
              .append(a.getPastEvents()).append("\n");
        }
        jTextAreaArtists.setText(sb.toString());
    }

    private void clearFields() {
        jTextFArtistName.setText("");
        jTextFContactInfo.setText("");
        jTextFTechReq.setText("");
        jTextFPastEvents.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextFTechReq = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFPastEvents = new javax.swing.JTextField();
        jButtonAddArtist = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Result = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaArtists = new javax.swing.JTextArea();
        jLabelResult = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonShowArtists = new javax.swing.JButton();
        jTextFArtistName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFContactInfo = new javax.swing.JTextField();

        jLabel3.setText("Technical Requirements:");

        jLabel4.setText("Past Events,(comma separated):");

        jButtonAddArtist.setText("Add Artist");

        jLabel5.setText("Show all Artist:");

        Result.setText("Result:");

        jTextAreaArtists.setColumns(20);
        jTextAreaArtists.setRows(5);
        jScrollPane1.setViewportView(jTextAreaArtists);

        jLabel1.setText("Artist Name:");

        jButtonShowArtists.setText("Show All Artist");

        jLabel2.setText("Contact Info:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonShowArtists)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButtonAddArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                            .addComponent(jTextFPastEvents, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFTechReq, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFContactInfo, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFArtistName, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(37, 37, 37))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFArtistName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFContactInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFTechReq, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFPastEvents, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButtonAddArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButtonShowArtists, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Result;
    private javax.swing.JButton jButtonAddArtist;
    private javax.swing.JButton jButtonShowArtists;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelResult;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaArtists;
    private javax.swing.JTextField jTextFArtistName;
    private javax.swing.JTextField jTextFContactInfo;
    private javax.swing.JTextField jTextFPastEvents;
    private javax.swing.JTextField jTextFTechReq;
    // End of variables declaration//GEN-END:variables
}
